# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minion <- function(filename) {
    .Call(`_rKraken_minion`, filename)
}

reaper <- function(filename) {
    .Call(`_rKraken_reaper`, filename)
}

tally <- function(filename) {
    .Call(`_rKraken_tally`, filename)
}

